[package]
name = "rusty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.19"
actix-web = "4.3.1"
actix-files = "0.6.2"
futures = "0.3.28"
tokio = "1.29.1"
tokio-util = "0.7.8"
